[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"
  included_files = ["netlify/functions/**"]

[functions.scheduled]
  schedule = "@hourly"
